### ISSUE TITLE
make UI even easier to use

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/dashboard#48]
They say: 

> "User interface is like a joke. If you have to explain it, its not that good."

My dream is for a brand new user to be able to use the dashboard with absolutely no questions from start to end.

This is a master ticket for tracking issues related to confusing elements of the UI:
- [ ] can you take a photo when the camera is off? 
- [ ] how do you exit from a zoomed in photo of video? https://github.com/wm-robo-ops/dashboard/issues/52
- [ ] what even is the bearing map?
- [ ] I can't read the DoF visualization! https://github.com/wm-robo-ops/dashboard/issues/51
- [ ] how do I match up rocks on the list to rocks on the map? https://github.com/wm-robo-ops/dashboard/issues/50
- [ ] can I delete photos? https://github.com/wm-robo-ops/dashboard/issues/25
- [ ] where on the map where these photos taken? https://github.com/wm-robo-ops/dashboard/issues/49
- ?
- ?
- ?

/cc @ajwells @wdconinc @Djruhnke @afnanenayet @Shenniey feel free to add more problems you see to the list. Also keep in mind Bird's comments about accessibility.
